name: Nativesons
favicon: null
layout_spectrum: 0.7897520302794874
typography_spectrum: 0.3569570027757436
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#376379'
    - '#5b8394'
    - '#7ea0b3'
    - '#b8c5cb'
    - '#374852'
  brandStrength: 1
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
